### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by felisida** [custom-components/sensor.file_restore#5]
I tried to set the component from UI, but when I click on "send" , it appears this error
![Schermata 2021-02-07 alle 12 06 19](https://user-images.githubusercontent.com/51525150/107144673-07d12280-693d-11eb-9d77-e6076b1ccb67.jpg)

**Comment by MapoDan** [comment]
Ciao,

a couple of questions:
- do you get the error on config flow or on option flow?
- do you had anything logged in home-assistant.log?
- are you using hass.io or a virtual environment?

Thanks
Daniele

**Comment by MapoDan** [comment]
I wasn't able to recreate the issue. 1y with no updates, closing topic
